package com.xeross.srapp.utils

object Constants {
    
    const val EXTRA_SUBCATEGORY_URL = "EXTRA_SUBCATEGORY_URL"
    const val EXTRA_CATEGORY_NAME = "EXTRA_CATEGORY_NAME"
    const val EXTRA_SUBCATEGORY_NAME = "EXTRA_SUBCATEGORY_NAME"
    const val EXTRA_SUBCATEGORY_ID = "EXTRA_SUBCATEGORY_ID"
    const val EXTRA_CATEGORY_ID = "EXTRA_CATEGORY_ID"
    
    const val DATABASE_COLLECTION_USERS = "users"
    const val DATABASE_COLLECTION_USERS_CATEGORIES = "users_categories"
    const val DATABASE_COLLECTION_CATEGORIES = "categories"
    const val DATABASE_COLLECTION_SUBCATEGORIES = "subcategories"
    const val DATABASE_COLLECTION_TIME = "times"
    
    const val KEY_SHARED_PREFERENCES = "KEY_SETTINGS_SHARED_PREFERENCES"
    const val SUBCATEGORY_BEST_TIME_SHARED_PREFERENCES = "SUBCATEGORY_BEST_TIME_SHARED_PREFERENCES"
}